### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by demist** [NickSHD/ProjectUnit#1]
+ нет схемы архитектуры
+ stat["long_range_damage"], не лучше ли было это было сделать, например, с помощью enum? 
а не строковые константы
+ Player(int); но ведь такая конструкция никоим образом не запрещает использовать конструктор по умолчанию. А кажется, что такое поведение некорректно

плюсы:
+ Initial_Values.h, это хороший тон выносить константы в отдельный файл

**Comment by NickSHD** [comment]
Для моей программы будет неудобен Enum, потому что если пользователь запросит статистику, например, о каком-то типе войнов, он введет строку, и придется писать большой switch, для того чтобы он вывел нужное количество.

**Comment by NickSHD** [comment]
И вопрос по поводу архитектуры, там же есть файл Architecture.txt, или в нем недостаточно описана архитектура?

**Comment by demist** [comment]
+необходимо добавить схему, а не только текстовое описание. 
+вместо switch каждый раз можно бы было сделать просто две функции - из строки в id и из id в строку
нужно доделать

**Comment by NickSHD** [comment]
Извиняюсь за задержку, добавлена схема архитектуры. По поводу enum я так и не понял, я не использую switch, а просто передаю в функцию нужную строку.

**Comment by NickSHD** [comment]
Окей, переписано под enum

**Comment by NickSHD** [comment]
Были внесены изменения

вт, 3 апр. 2018 г., 17:54 Nikita Starichkov <notifications@github.com>:

**Comment by demist** [comment]
засчитано
